# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' dggglm
#'
#' Solve the least square problem
#'
#' Solve the following least square problem:
#' \deqn{\min_x || B^{-1} (d - A x) ||_2}
#' \describe{
#'   \item{WORK}{(workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)).
#'               On exit, if INFO = 0, WORK(1) returns the optimal LWORK.}
#'   \item{LWORK}{(input) INTEGER.
#'               The dimension of the array WORK. LWORK >= max(1,N+M+P).
#'               For optimum performance, LWORK >= M+min(N,P)+max(N,P)*NB,
#'               where NB is an upper bound for the optimal blocksizes for
#'               DGEQRF, SGERQF, DORMQR and SORMRQ.
#'               If LWORK = -1, then a workspace query is assumed; the routine
#'               only calculates the optimal size of the WORK array, returns
#'               this value as the first entry of the WORK array, and no error
#'               message related to LWORK is issued by XERBLA.}
#'   \item{INFO}{(output) INTEGER.
#'     \describe{
#'       \item{= 0}{successful exit.}
#'       \item{< 0}{if INFO = -i, the i-th argument had an illegal value.}
#'       \item{= 1}{the upper triangular factor R associated with A in the
#'                  generalized QR factorization of the pair (A, B) is
#'                  singular, so that rank(A) < M; the least squares
#'                  solution could not be computed.}
#'       \item{= 2}{the bottom (N-M) by (N-M) part of the upper trapezoidal
#'                  factor T associated with B in the generalized QR
#'                  factorization of the pair (A, B) is singular, so that
#'                  rank( A B ) < N; the least squares solution could not
#'                  be computed.}
#'       }}
#' }
#'
#' @param A A matrix A (dimension n,m)
#' @param B A matrix B (dimension n,p)
#' @param d A vector d. dimension n
#' @param NB An integer indicating an upper bound for the optimal blocksizes. The default is 64.
#' @return A list with components;
#' \item{x}{A vector m. dimension m}
#' \item{y}{A vector p. dimension p}
#' \item{info}{A status. See details.}
#'
#' @export
dggglm <- function(A, B, d, NB = 64L) {
    .Call('_Rsrat_dggglm', PACKAGE = 'Rsrat', A, B, d, NB)
}

#' @rdname em
em_exp_emstep <- function(params, data) {
    .Call('_Rsrat_em_exp_emstep', PACKAGE = 'Rsrat', params, data)
}

#' @rdname em
em_gamma_emstep <- function(params, data, divide = 15L, eps = 1.0e-10) {
    .Call('_Rsrat_em_gamma_emstep', PACKAGE = 'Rsrat', params, data, divide, eps)
}

#' @rdname em
em_llogis_emstep <- function(params, data) {
    .Call('_Rsrat_em_llogis_emstep', PACKAGE = 'Rsrat', params, data)
}

#' @rdname em
em_lnorm_emstep <- function(params, data) {
    .Call('_Rsrat_em_lnorm_emstep', PACKAGE = 'Rsrat', params, data)
}

#' @rdname em
em_lxvmax_emstep <- function(params, data) {
    .Call('_Rsrat_em_lxvmax_emstep', PACKAGE = 'Rsrat', params, data)
}

#' @rdname em
em_lxvmin_emstep <- function(params, data) {
    .Call('_Rsrat_em_lxvmin_emstep', PACKAGE = 'Rsrat', params, data)
}

#' @rdname em
em_pareto_emstep <- function(params, data) {
    .Call('_Rsrat_em_pareto_emstep', PACKAGE = 'Rsrat', params, data)
}

#' @rdname em
em_tlogis_emstep <- function(params, data) {
    .Call('_Rsrat_em_tlogis_emstep', PACKAGE = 'Rsrat', params, data)
}

#' @rdname em
em_tnorm_emstep <- function(params, data) {
    .Call('_Rsrat_em_tnorm_emstep', PACKAGE = 'Rsrat', params, data)
}

#' @rdname em
em_txvmax_emstep <- function(params, data) {
    .Call('_Rsrat_em_txvmax_emstep', PACKAGE = 'Rsrat', params, data)
}

#' @rdname em
em_txvmin_emstep <- function(params, data) {
    .Call('_Rsrat_em_txvmin_emstep', PACKAGE = 'Rsrat', params, data)
}

#' @rdname gumbel
#' @export
dgumbel <- function(x, loc = 0, scale = 1, log = FALSE, min = FALSE) {
    .Call('_Rsrat_dgumbel', PACKAGE = 'Rsrat', x, loc, scale, log, min)
}

#' @rdname gumbel
#' @export
pgumbel <- function(q, loc = 0, scale = 1, lower = TRUE, log = FALSE, min = FALSE) {
    .Call('_Rsrat_pgumbel', PACKAGE = 'Rsrat', q, loc, scale, lower, log, min)
}

#' @rdname gumbel
#' @export
qgumbel <- function(p, loc = 0, scale = 1, lower = TRUE, log = FALSE, min = FALSE) {
    .Call('_Rsrat_qgumbel', PACKAGE = 'Rsrat', p, loc, scale, lower, log, min)
}

